sonar.projectKey=postmill-ai_postmill-app
sonar.projectName=Postmill App
sonar.projectDescription=An Open-Source Social Media Scheduler

# Scan Performace
sonar.javascript.node.maxspace=24576
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.spec.ts,**/*.test.ts,*.png
