import React from 'react';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { DailyBrief } from './daily.brief';

const push = vi.fn();
const mockShow = vi.fn();
const mockGenerate = vi.fn();

vi.mock('@postmill-ai/react/translation/get.transation.service.client', () => ({
  useT: () => (_key: string, fallback: string) => fallback,
}));

vi.mock('next/navigation', () => ({
  useRouter: () => ({ push }),
}));

vi.mock('@postmill-ai/react/toaster/toaster', () => ({
  useToaster: () => ({ show: mockShow }),
}));

vi.mock('@postmill-ai/frontend/components/layout/use-ai-active', () => ({
  useAiActive: vi.fn(),
  AI_SETUP_HREF: '/settings/ai/llm-providers',
}));

vi.mock('../hooks/useDailyBrief', () => ({
  useDailyBrief: vi.fn(),
}));

vi.mock('@postmill-ai/frontend/components/analytics/kit/states', () => ({
  TabSkeleton: ({ variant }: { variant?: string }) => (
    <div data-testid="tab-skeleton" data-variant={variant} />
  ),
  EmptyState: ({ title }: { title?: string }) => <div>{title}</div>,
}));

vi.mock('@postmill-ai/react/form/button', () => ({
  Button: ({ children, onClick }: any) => (
    <button type="button" onClick={onClick}>
      {children}
    </button>
  ),
}));

import { useAiActive } from '@postmill-ai/frontend/components/layout/use-ai-active';
import { useDailyBrief } from '../hooks/useDailyBrief';

const mockAiActive = useAiActive as unknown as ReturnType<typeof vi.fn>;
const mockBriefHook = useDailyBrief as unknown as ReturnType<typeof vi.fn>;

describe('DailyBrief', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockAiActive.mockReturnValue(true);
    mockBriefHook.mockReturnValue({
      data: undefined,
      error: undefined,
      isLoading: true,
      generate: mockGenerate,
    });
  });

  it('returns null when AI is not active', () => {
    mockAiActive.mockReturnValue(false);
    const { container } = render(<DailyBrief />);
    expect(container.firstChild).toBeNull();
  });

  it('shows a loading skeleton while the brief is loading', () => {
    render(<DailyBrief />);
    expect(screen.getByText('Loading…')).toBeTruthy();
  });

  it('expands and shows cached brief text without calling generate', () => {
    mockBriefHook.mockReturnValue({
      data: { brief: 'Your posts are performing well. Focus on replies.', generatedAt: '2026-01-01T00:00:00Z' },
      error: undefined,
      isLoading: false,
      generate: mockGenerate,
    });

    render(<DailyBrief />);
    fireEvent.click(screen.getByText('Daily Brief'));

    expect(screen.getByTestId('daily-brief-body').textContent).toBe('Your posts are performing well. Focus on replies.');
    expect(screen.getByText('Generated by AI')).toBeTruthy();
    expect(mockGenerate).not.toHaveBeenCalled();
  });

  it('calls generate when expanded and no cached brief exists', async () => {
    mockGenerate.mockResolvedValue({ brief: 'Generated brief.', generatedAt: '2026-01-01T00:00:00Z' });
    mockBriefHook.mockReturnValue({
      data: { cached: false },
      error: undefined,
      isLoading: false,
      generate: mockGenerate,
    });

    render(<DailyBrief />);
    fireEvent.click(screen.getByText('Daily Brief'));

    await waitFor(() => {
      expect(mockGenerate).toHaveBeenCalledTimes(1);
    });
  });

  it('shows 429 budget message when generate fails with 429', () => {
    const err: any = new Error('Over budget');
    err.status = 429;
    mockBriefHook.mockReturnValue({
      data: undefined,
      error: err,
      isLoading: false,
      generate: mockGenerate,
    });

    render(<DailyBrief open />);

    expect(screen.getByText('AI budget exceeded. Briefs will resume after your budget resets.')).toBeTruthy();
  });

  it('redirects to AI setup on 503 error', async () => {
    const err: any = new Error('AI not configured');
    err.status = 503;
    mockGenerate.mockRejectedValue(err);
    mockBriefHook.mockReturnValue({
      data: { cached: false },
      error: undefined,
      isLoading: false,
      generate: mockGenerate,
    });

    render(<DailyBrief />);
    fireEvent.click(screen.getByText('Daily Brief'));

    await waitFor(() => {
      expect(push).toHaveBeenCalledWith('/settings/ai/llm-providers');
    });
  });

  it('respects controlled open prop', () => {
    mockBriefHook.mockReturnValue({
      data: { brief: 'Teaser. Body content here.', generatedAt: '2026-01-01T00:00:00Z' },
      error: undefined,
      isLoading: false,
      generate: mockGenerate,
    });

    render(<DailyBrief open />);
    expect(screen.getByTestId('daily-brief-body').textContent).toBe('Teaser. Body content here.');
    expect(screen.getByText('Regenerate')).toBeTruthy();
  });
});

// The dashboard renders this controlled — `open` is always a boolean, never
// undefined. Every expand test above renders it UNCONTROLLED, which is why the
// production card shipped completely inert: the internal setter was a no-op, and
// because expanding is what triggers generation, a workspace with no cached brief
// could never produce one.
describe('DailyBrief controlled mode', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockAiActive.mockReturnValue(true);
    mockBriefHook.mockReturnValue({
      data: { cached: false },
      error: undefined,
      isLoading: false,
      generate: mockGenerate,
    });
  });

  it('asks the parent to open when the header is clicked', () => {
    const onOpenChange = vi.fn();
    render(<DailyBrief open={false} onOpenChange={onOpenChange} />);

    fireEvent.click(screen.getByRole('button', { name: /daily brief/i }));

    expect(onOpenChange).toHaveBeenCalledWith(true);
  });

  it('generates a brief when opened with nothing cached', async () => {
    const onOpenChange = vi.fn();
    render(<DailyBrief open={false} onOpenChange={onOpenChange} />);

    fireEvent.click(screen.getByRole('button', { name: /daily brief/i }));

    await waitFor(() => expect(mockGenerate).toHaveBeenCalled());
  });

  it('asks the parent to close when it is already open', () => {
    const onOpenChange = vi.fn();
    render(<DailyBrief open onOpenChange={onOpenChange} />);

    fireEvent.click(screen.getByRole('button', { name: /daily brief/i }));

    expect(onOpenChange).toHaveBeenCalledWith(false);
    // Collapsing must not kick off another generation.
    expect(mockGenerate).not.toHaveBeenCalled();
  });

  it('does not re-generate when a brief is already cached', () => {
    mockBriefHook.mockReturnValue({
      data: { brief: 'cached text', generatedAt: '2026-01-01T00:00:00Z' },
      error: undefined,
      isLoading: false,
      generate: mockGenerate,
    });
    const onOpenChange = vi.fn();
    render(<DailyBrief open={false} onOpenChange={onOpenChange} />);

    fireEvent.click(screen.getByRole('button', { name: /daily brief/i }));

    expect(onOpenChange).toHaveBeenCalledWith(true);
    expect(mockGenerate).not.toHaveBeenCalled();
  });
});
